name: Testeee

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
      working-directory: ./C00/ex00/
     # Add a step to run the executable before cleaning
    - name: Run the executable
      run: ./megaphone "oi migos como estamos?" >> test.txt
      working-directory: ./C00/ex00/

